Bugfixes after Sprint 2 (#15)
* Resolved :
WARN[0000] /home/alfur/selfedu/core_backend/docker-compose.test.yml: `version` is obsolete
during building|running containers

* managers.py -- fixed:
TypeError: user.models.User() got multiple values for keyword argument 'username'
while creating user with username provided

serializers.py -- fixed: field username is not included to fill during registration.

* Resolved :
WARN[0000] /home/alfur/selfedu/core_backend/docker-compose.yml: `version` is obsolete
during building|running containers

* DO NOT DELETE
env_file:
 - .env
NEVER!!!

* Fixed token-related tests after changes in urls.py

Fixed broken test of GET (get user) endpoint (needed force_authorization)

* serializers.py - According to OpenApi Schema UserRetrieveUpdateDestroySerializer must retrieve next set of fields
("pk", "username", "email", "avatar")

views.py - According to OpenApi Schema UserCreateAPIView on the proper(valid) POST request must send response with empty body and status 201

* tested CRUD endpoints for user

* linters